CREATE TABLE IF NOT EXISTS `courses` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
    `price` FLOAT NOT NULL,
    `image_url` VARCHAR(255) NOT NULL,
    `category` VARCHAR(255) NOT NULL,
    `author` VARCHAR(255) NOT NULL,
    `duration` INT(11) NOT NULL,
    `rating` FLOAT NOT NULL,
    `is_featured` BOOLEAN NOT NULL DEFAULT FALSE,
    `is_published` BOOLEAN NOT NULL DEFAULT FALSE,
    `total_enrollments` INT(11) NOT NULL DEFAULT 0,
    `total_lessons` INT(11) NOT NULL DEFAULT 0,
    `is_active` BOOLEAN NOT NULL DEFAULT FALSE,
    `is_resource` BOOLEAN NOT NULL DEFAULT FALSE,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_courses_name` (`name`),
    INDEX `idx_courses_category` (`category`),
    INDEX `idx_courses_author` (`author`),
    INDEX `idx_courses_is_featured` (`is_featured`),
    INDEX `idx_courses_is_published` (`is_published`),
    INDEX `idx_courses_is_active` (`is_active`),
    INDEX `idx_courses_is_resource` (`is_resource`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
